2023-08-18 11:06:20,518 INFO    MainThread:47511 [internal.py:wandb_internal():90] W&B internal server running at pid: 47511, started at: 2023-08-18 11:06:20.518631
2023-08-18 11:06:20,521 DEBUG   HandlerThread:47511 [handler.py:handle_request():141] handle_request: run_start
2023-08-18 11:06:20,521 INFO    WriterThread:47511 [datastore.py:open_for_write():75] open: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_110620-315ct9ac/run-315ct9ac.wandb
2023-08-18 11:06:20,522 DEBUG   HandlerThread:47511 [meta.py:__init__():35] meta init
2023-08-18 11:06:20,522 DEBUG   HandlerThread:47511 [meta.py:__init__():49] meta init done
2023-08-18 11:06:20,522 DEBUG   HandlerThread:47511 [meta.py:probe():209] probe
2023-08-18 11:06:20,523 DEBUG   HandlerThread:47511 [meta.py:_setup_git():199] setup git
2023-08-18 11:06:20,532 DEBUG   HandlerThread:47511 [meta.py:_setup_git():206] setup git done
2023-08-18 11:06:20,532 DEBUG   HandlerThread:47511 [meta.py:_save_pip():53] save pip
2023-08-18 11:06:20,532 DEBUG   HandlerThread:47511 [meta.py:_save_pip():67] save pip done
2023-08-18 11:06:20,532 DEBUG   HandlerThread:47511 [meta.py:probe():247] probe done
2023-08-18 11:06:21,733 WARNING MainThread:47511 [internal.py:wandb_internal():153] Internal process interrupt: 1
2023-08-18 11:06:21,894 WARNING MainThread:47511 [internal.py:wandb_internal():153] Internal process interrupt: 2
2023-08-18 11:06:21,894 ERROR   MainThread:47511 [internal.py:wandb_internal():156] Internal process interrupted.
2023-08-18 11:06:22,521 INFO    SenderThread:47511 [sender.py:finish():1111] shutting down sender
2023-08-18 11:06:22,734 INFO    WriterThread:47511 [datastore.py:close():279] close: /home/nicole/marl-emecom/src/experiments_anastassacos/wandb/offline-run-20230818_110620-315ct9ac/run-315ct9ac.wandb
2023-08-18 11:06:22,735 INFO    HandlerThread:47511 [handler.py:finish():806] shutting down handler
2023-08-18 11:06:22,735 INFO    MainThread:47511 [internal.py:handle_exit():80] Internal process exited
